name: Build blog with org-mode, deploy to pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: '28.1'
          
      - name: Publish org to html
        run: ./orgpublish.sh
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
